//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 09:47:18 AM BST 
//


package com.lindar.id3global.internal.vo;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DownloadResult" type="{http://schemas.microsoft.com/Message}StreamBody"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "downloadResult"
})
@XmlRootElement(name = "DownloadResponse")
public class DownloadResponse {

    @XmlElement(name = "DownloadResult", required = true)
    protected byte[] downloadResult;

    /**
     * Gets the value of the downloadResult property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDownloadResult() {
        return downloadResult;
    }

    /**
     * Sets the value of the downloadResult property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDownloadResult(byte[] value) {
        this.downloadResult = value;
    }

}
