//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 09:47:18 AM BST 
//


package com.lindar.id3global.internal.vo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalProfileState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GlobalProfileState"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Test"/&gt;
 *     &lt;enumeration value="PreEffective"/&gt;
 *     &lt;enumeration value="Effective"/&gt;
 *     &lt;enumeration value="Retired"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GlobalProfileState")
@XmlEnum
public enum GlobalProfileState {

    @XmlEnumValue("Test")
    TEST("Test"),
    @XmlEnumValue("PreEffective")
    PRE_EFFECTIVE("PreEffective"),
    @XmlEnumValue("Effective")
    EFFECTIVE("Effective"),
    @XmlEnumValue("Retired")
    RETIRED("Retired");
    private final String value;

    GlobalProfileState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GlobalProfileState fromValue(String v) {
        for (GlobalProfileState c: GlobalProfileState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
