//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 09:47:18 AM BST 
//


package com.lindar.id3global.internal.vo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalBankingDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalBankingDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BankAccount" type="{http://www.id3global.com/ID3gWS/2013/04}GlobalBankAccount" minOccurs="0"/&gt;
 *         &lt;element name="CreditDebitCard" type="{http://www.id3global.com/ID3gWS/2013/04}GlobalCreditDebitCard" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalBankingDetails", propOrder = {
    "bankAccount",
    "creditDebitCard"
})
public class GlobalBankingDetails {

    @XmlElementRef(name = "BankAccount", namespace = "http://www.id3global.com/ID3gWS/2013/04", type = JAXBElement.class, required = false)
    protected JAXBElement<GlobalBankAccount> bankAccount;
    @XmlElementRef(name = "CreditDebitCard", namespace = "http://www.id3global.com/ID3gWS/2013/04", type = JAXBElement.class, required = false)
    protected JAXBElement<GlobalCreditDebitCard> creditDebitCard;

    /**
     * Gets the value of the bankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GlobalBankAccount }{@code >}
     *     
     */
    public JAXBElement<GlobalBankAccount> getBankAccount() {
        return bankAccount;
    }

    /**
     * Sets the value of the bankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GlobalBankAccount }{@code >}
     *     
     */
    public void setBankAccount(JAXBElement<GlobalBankAccount> value) {
        this.bankAccount = value;
    }

    /**
     * Gets the value of the creditDebitCard property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GlobalCreditDebitCard }{@code >}
     *     
     */
    public JAXBElement<GlobalCreditDebitCard> getCreditDebitCard() {
        return creditDebitCard;
    }

    /**
     * Sets the value of the creditDebitCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GlobalCreditDebitCard }{@code >}
     *     
     */
    public void setCreditDebitCard(JAXBElement<GlobalCreditDebitCard> value) {
        this.creditDebitCard = value;
    }

}
