//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 09:47:18 AM BST 
//


package com.lindar.id3global.internal.vo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalUKData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalUKData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Passport" type="{http://www.id3global.com/ID3gWS/2013/04}GlobalUKPassport" minOccurs="0"/&gt;
 *         &lt;element name="DrivingLicence" type="{http://www.id3global.com/ID3gWS/2013/04}GlobalUKDrivingLicence" minOccurs="0"/&gt;
 *         &lt;element name="NationalInsuranceNumber" type="{http://www.id3global.com/ID3gWS/2013/04}GlobalUKNationalInsuranceNumber" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalUKData", propOrder = {
    "passport",
    "drivingLicence",
    "nationalInsuranceNumber"
})
public class GlobalUKData {

    @XmlElementRef(name = "Passport", namespace = "http://www.id3global.com/ID3gWS/2013/04", type = JAXBElement.class, required = false)
    protected JAXBElement<GlobalUKPassport> passport;
    @XmlElementRef(name = "DrivingLicence", namespace = "http://www.id3global.com/ID3gWS/2013/04", type = JAXBElement.class, required = false)
    protected JAXBElement<GlobalUKDrivingLicence> drivingLicence;
    @XmlElementRef(name = "NationalInsuranceNumber", namespace = "http://www.id3global.com/ID3gWS/2013/04", type = JAXBElement.class, required = false)
    protected JAXBElement<GlobalUKNationalInsuranceNumber> nationalInsuranceNumber;

    /**
     * Gets the value of the passport property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKPassport }{@code >}
     *     
     */
    public JAXBElement<GlobalUKPassport> getPassport() {
        return passport;
    }

    /**
     * Sets the value of the passport property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKPassport }{@code >}
     *     
     */
    public void setPassport(JAXBElement<GlobalUKPassport> value) {
        this.passport = value;
    }

    /**
     * Gets the value of the drivingLicence property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKDrivingLicence }{@code >}
     *     
     */
    public JAXBElement<GlobalUKDrivingLicence> getDrivingLicence() {
        return drivingLicence;
    }

    /**
     * Sets the value of the drivingLicence property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKDrivingLicence }{@code >}
     *     
     */
    public void setDrivingLicence(JAXBElement<GlobalUKDrivingLicence> value) {
        this.drivingLicence = value;
    }

    /**
     * Gets the value of the nationalInsuranceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKNationalInsuranceNumber }{@code >}
     *     
     */
    public JAXBElement<GlobalUKNationalInsuranceNumber> getNationalInsuranceNumber() {
        return nationalInsuranceNumber;
    }

    /**
     * Sets the value of the nationalInsuranceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link GlobalUKNationalInsuranceNumber }{@code >}
     *     
     */
    public void setNationalInsuranceNumber(JAXBElement<GlobalUKNationalInsuranceNumber> value) {
        this.nationalInsuranceNumber = value;
    }

}
