//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.17 at 09:47:18 AM BST 
//


package com.lindar.id3global.internal.vo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalResidenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GlobalResidenceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HomeOwnerOutright"/&gt;
 *     &lt;enumeration value="HomeOwnerMortgage"/&gt;
 *     &lt;enumeration value="Tenant"/&gt;
 *     &lt;enumeration value="LivingWithRelatives"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GlobalResidenceType")
@XmlEnum
public enum GlobalResidenceType {

    @XmlEnumValue("HomeOwnerOutright")
    HOME_OWNER_OUTRIGHT("HomeOwnerOutright"),
    @XmlEnumValue("HomeOwnerMortgage")
    HOME_OWNER_MORTGAGE("HomeOwnerMortgage"),
    @XmlEnumValue("Tenant")
    TENANT("Tenant"),
    @XmlEnumValue("LivingWithRelatives")
    LIVING_WITH_RELATIVES("LivingWithRelatives");
    private final String value;

    GlobalResidenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GlobalResidenceType fromValue(String v) {
        for (GlobalResidenceType c: GlobalResidenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
